# Generated by Django 6.0.5 on 2026-06-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('stars', models.IntegerField(default=3, verbose_name='Звёзды')),
                ('price_per_night', models.IntegerField(verbose_name='Цена за ночь (руб.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3, verbose_name='Рейтинг')),
            ],
        ),
    ]
