# Generated by Django 6.0.5 on 2026-06-11 19:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywapp', '0002_hotel_delete_guest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Фото отеля'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lat',
            field=models.FloatField(default=55.7558, verbose_name='Широта (Latitude)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='lng',
            field=models.FloatField(default=37.6173, verbose_name='Долгота (Longitude)'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество звезд'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100, verbose_name='Тип номера (например, Стандарт, Люкс)')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('capacity', models.IntegerField(verbose_name='Вместимость (чел.)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для бронирования')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mywapp.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mywapp.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
