# Generated by Django 6.0.5 on 2026-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywapp', '0003_alter_hotel_options_remove_hotel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='lng',
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night',
            field=models.IntegerField(default=3000, verbose_name='Цена за ночь (руб.)'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='property_type',
            field=models.CharField(choices=[('hotel', 'Отель'), ('apartment', 'Квартира'), ('house', 'Дом и коттедж'), ('hostel', 'Хостел')], default='hotel', max_length=20, verbose_name='Тип жилья'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=3, verbose_name='Количество звезд'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
