# Generated by Django 6.0.5 on 2026-06-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywapp', '0004_remove_room_hotel_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='booked_from',
            field=models.DateField(blank=True, null=True, verbose_name='Занят с'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='booked_to',
            field=models.DateField(blank=True, null=True, verbose_name='Занят по'),
        ),
    ]
