# Generated by Django 6.0.5 on 2026-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywapp', '0005_hotel_booked_from_hotel_booked_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='has_breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак включен'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='Бассейн'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_wifi',
            field=models.BooleanField(default=True, verbose_name='Бесплатный Wi-Fi'),
        ),
    ]
