# Generated by Django 6.0.5 on 2026-06-12 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywapp', '0006_hotel_has_breakfast_hotel_has_pool_hotel_has_wifi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='booked_from',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='booked_to',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_breakfast',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_pool',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='property_type',
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Дата заезда')),
                ('checkout', models.DateField(verbose_name='Дата выезда')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('property_type', models.CharField(choices=[('hotel', 'Отель'), ('apartment', 'Квартира'), ('house', 'Дом и коттедж'), ('hostel', 'Хостел')], default='hotel', max_length=20, verbose_name='Тип жилья')),
                ('booked_from', models.DateField(blank=True, null=True, verbose_name='Занят с')),
                ('booked_to', models.DateField(blank=True, null=True, verbose_name='Занят по')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Бесплатный Wi-Fi')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('has_breakfast', models.BooleanField(default=False, verbose_name='Завтрак включен')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mywapp.hotel', verbose_name='Отель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
