# Generated by Django 6.0.5 on 2026-06-18 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywapp', '0007_remove_hotel_booked_from_remove_hotel_booked_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема сообщения')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('property_type', models.CharField(choices=[('hotel', 'Отель'), ('apartment', 'Квартира'), ('house', 'Дом и коттедж'), ('hostel', 'Хостел')], default='hotel', max_length=20, verbose_name='Тип жилья')),
                ('booked_from', models.DateField(blank=True, null=True, verbose_name='Занят с')),
                ('booked_to', models.DateField(blank=True, null=True, verbose_name='Занят по')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Бесплатный Wi-Fi')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('has_breakfast', models.BooleanField(default=False, verbose_name='Завтрак включен')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_from',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booked_to',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_breakfast',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_pool',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='property_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='mywapp.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
